/**
 * Design tokens — generated by generate-design-brief.sh
 * DO NOT edit manually. Regenerate with: FORCE_DESIGN=1 bash /root/agent-factory/scripts/generate-design-brief.sh /root/agent-factory/projects/startupsignal "Intelligence dashboard aggregating startup ideas from top incubators, cross-referenced against failed startups, with LaunchabilityScore and Execution Briefs"
 *
 * Personality: dev-tool
 * Vision: Signal meets pattern recognition: where startup momentum meets market gravity
 */

export const design = {
  // Backgrounds
  bg: {
    primary: "#0A0F1A", // page background (OLED near-black)
    surface: "#0F1419", // card / panel backgrounds
    elevated: "#141921", // modals, dropdowns, tooltips
    glass: "rgba(255,255,255,0.04)",
  },

  // Text
  text: {
    primary: "rgba(255,255,255,0.87)",
    secondary: "rgba(255,255,255,0.60)",
    muted: "rgba(255,255,255,0.35)",
    inverse: "rgba(0,0,0,0.87)",
  },

  // Borders
  border: {
    subtle: "rgba(255,255,255,0.08)",
    default: "rgba(255,255,255,0.12)",
    emphasis: "rgba(255,255,255,0.20)",
  },

  // Accent (unique per project)
  accent: {
    base: "#F59E0B",
    glow: "#F59E0B33", // 20% opacity for shadows/glows
    hover: "#F59E0Bcc", // 80% opacity for hover states
    subtle: "#F59E0B1a", // 10% opacity for backgrounds
  },

  // Typography
  font: {
    sans: "'Space Grotesk', system-ui, sans-serif",
    mono: "'JetBrains Mono', 'Courier New', monospace",
  },

  // Motion (Spring defaults)
  spring: {
    fast: { type: "spring", stiffness: 400, damping: 30 } as const,
    default: { type: "spring", stiffness: 350, damping: 25 } as const,
    slow: { type: "spring", stiffness: 200, damping: 20 } as const,
  },

  // Personality: "dev-tool"
  personality: "dev-tool" as const,
} as const;

export type DesignPersonality = typeof design.personality;
